### PR TITLE
Ft preserve data

### PR DESCRIPTION
**Pull request by Moathal**
### Project requirements
- Check the documentation for Ruby's [JSON library](https://ruby-doc.org/stdlib-3.0.0/libdoc/json/rdoc/JSON.html).
- On exit from your app save all the data (books, people, and rentals) into JSON files. One per type of data you are storing and named accordingly (e.g. `rentals.json`)
- On startup of your app load all data from files. Remember to handle the case when one or more of the files are missing.

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



Screenshot from 2022-10-20 09-38-51

## Highlights :green_circle: 


- Correct Gitflow :heavy_check_mark: 
- PR has a good title and summary :heavy_check_mark: 
- Descriptive README.md file.
- Correct GitHub flow :+1: 



## Required Changes ♻️

- I got the console error when I try to run your app. Kindly check out the screenshot below:

Screenshot from 2022-11-17 05-51-28

- Hence I couldn't continue to check if the data is actually preserved.


_Check the comments under the review._

## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Moathal** [comment]
Apparently, there is a conflict in the JSON files that's why there is such an error. You just need to delete the info in the JSON file @FrederickMih

**Comment by FrederickMih** [comment]
> Apparently, there is a conflict in the JSON files that's why there is such an error. You just need to delete the info in the JSON file @FrederickMih

Nice 👍. Always double check before submitting.

**Comment by Moathal** [comment]
JSON file holds dummy data that has been saved to check if the app works. This conflict has not been mentioned in GitHub

**Review by Davidosky007 — APPROVED** [review]
Hi @Moathal @iambenkis @peterboro 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Proper use of Gitflow 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
